#!/bin/bash
if [[ "$1" == "stop" ]]
then
IFS=' '
PID=`pidof watch`
read -ra ADDR <<<"$PID"
  
for i in "${ADDR[@]}"; 
do  
kill $i  
done  
echo "process killed"
exit
fi

VAL=$2;

if [ "$VAL" == "" ]; then
  VAL=-1
fi

#check if value 

if  [[ "$scale" =~ ^[0-9]+$ ]]
    then
        if [ $VAL -ge 0 ]; then
          ISNUM=true
fi
fi




if [[ "$1" == "set" ]]
then
   if [[ "$ISNUM" == "true" ]]; then
      watch -n $VAL setwallpaper.sh > /dev/null & disown
      echo "wallpaper changing every $VAL seconds"
      echo "type 'redwall stop' to stop"
      exec
  fi
fi

if [[ "$1" == "change" ]]
then
  shift
  setwallpaper.sh $@
fi




if [[ "$1" == "config" ]]
then
   xdg-open /home/`whoami`/.RedditWallPaper/redditConfig.json
fi
